l_russian:
strong_RAS: "Усилить Россию"
strong_CHI: "Усилить Российскую Чечню"
strong_CHE: "Усилить Чечню"
strong_SAK: "Усилить Грузию"
strong_AZR: "Усилить Азербайджан"
strong_ARM: "Усилить Армению"
strong_DAG: "Усилить Дагестан"
strong_ABK: "Усилить Абхазию"
strong_ING: "Усилить Ингушетию"
strong_OST: "Усилить Осетию"
strong_TUR: "Усилить Турцию"
strong_ADY: "Усилить Адыгею"
strong_KLM: "Усилить Калмыкию"
strong_PER: "Усилить Иран"
strong_ADJ: "Усилить Аджарию"
strong_ARS: "Усилить Арцах"
strong_KBK: "Усилить Кабардино-Балкарию"
strong_KCC: "Усилить Карачаево-Черкесию"
strong_GOM: "Усилить правительство Гамсахурдии"
strong_KAZ: "Усилить Казахстан"
strong_TKM: "Усилить Туркменистан"