l_english:
strong_RAS: "Strengthen Russia"
strong_CHI: "Strengthen Russian Chechnya"
strong_CHE: "Strengthen Chechnya"
strong_SAK: "Strengthen Georgia"
strong_AZR: "Strengthen Azerbaijan"
strong_ARM: "Strengthen Armenia"
strong_DAG: "Strengthen Dagestan"
strong_ABK: "Strengthen Abkhazia"
strong_ING: "Strengthen Ingushetia"
strong_OST: "Strengthen Ossetia"
strong_TUR: "Strengthen Turkey"
strong_ADY: "Strengthen Adygea"
strong_KLM: "Strengthen Kalmykia"
strong_PER: "Strengthen Iran"
strong_ADJ: "Strengthen Adjara"
strong_ARS: "Strengthen Artsakh"
strong_KBK: "Strengthen Kabardino-Balkaria"
strong_KCC: "Strengthen Karachay-Cherkessia"
strong_GOM: "Strengthen the Gamsakhurdia Government"
strong_KAZ: "Strengthen Kazakhstan"
strong_TKM: "Strengthen Turkmenistan"