l_english:
strong_RAS: "Strengthen Russia"
strong_CHI: "Strengthen Russian Chechnya"
strong_CHE: "Strengthen Chechnya"
strong_SAK: "Strengthen Georgia"
strong_AZR: "Strengthen Azerbaijan"
strong_ARM: "Strengthen Armenia"
strong_DAG: "Strengthen Dagestan"
strong_ABK: "Strengthen Abkhazia"
strong_ING: "Strengthen Ingushetia"
strong_OST: "Strengthen Ossetia"
strong_TUR: "Strengthen Turkey"
strong_ADY: "Strengthen Adygea"
strong_KLM: "Strengthen Kalmykia"
strong_PER: "Strengthen Iran"
strong_ADJ: "Strengthen Adjara"
strong_ARS: "Strengthen Artsakh"
strong_KBK: "Strengthen Kabardino-Balkaria"
strong_KCC: "Strengthen Karachay-Cherkessia"
strong_GOM: "Strengthen the Gamsakhurdia Government"
strong_KAZ: "Strengthen Kazakhstan"
strong_TKM: "Strengthen Turkmenistan"
RULE_MOD_SETTINGS: "Mod Settings"
WAL_ANNEX: "Game Optimization"
WAL_ANNEX_OFF: "Normal Game"
WAL_ANNEX_OFF_DESC: "The game will proceed without any changes."
WAL_ANNEX_ON: "Disable Central Asian Countries"
WAL_ANNEX_ON_DESC: "All Central Asian countries will be merged into one."
WALL_ANNEX_ON: "Disable Countries Without Content"
WALL_ANNEX_ON_DESC: "All countries without content will be merged into one."